$(document).ready(function() {
setTimeout(function(){ // Allow PINT to load first


(function(root,factory){if(typeof exports==="object")module.exports=factory();else if(typeof define==="function"&&define.amd)define("salvattore",[],factory);else root.salvattore=factory()})(this,function(){if(!Function.prototype.bind)Function.prototype.bind=function(oThis){if(typeof this!=="function")throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var aArgs=Array.prototype.slice.call(arguments,1),fToBind=this,FNOP=function(){},fBound=function(){return fToBind.apply(this instanceof
FNOP&&oThis?this:oThis,aArgs.concat(Array.prototype.slice.call(arguments)))};FNOP.prototype=this.prototype;fBound.prototype=new FNOP;return fBound};(function(){var ObjectProto=Object.prototype,defineGetter=ObjectProto.__defineGetter__,defineSetter=ObjectProto.__defineSetter__,lookupGetter=ObjectProto.__lookupGetter__,lookupSetter=ObjectProto.__lookupSetter__,hasOwnProp=ObjectProto.hasOwnProperty;if(defineGetter&&(defineSetter&&(lookupGetter&&lookupSetter))){if(!Object.defineProperty)Object.defineProperty=
function(obj,prop,descriptor){if(arguments.length<3)throw new TypeError("Arguments not optional");prop+="";if(hasOwnProp.call(descriptor,"value")){if(!lookupGetter.call(obj,prop)&&!lookupSetter.call(obj,prop))obj[prop]=descriptor.value;if(hasOwnProp.call(descriptor,"get")||hasOwnProp.call(descriptor,"set"))throw new TypeError("Cannot specify an accessor and a value");}if(!(descriptor.writable&&(descriptor.enumerable&&descriptor.configurable)))throw new TypeError("This implementation of Object.defineProperty does not support"+
" false for configurable, enumerable, or writable.");if(descriptor.get)defineGetter.call(obj,prop,descriptor.get);if(descriptor.set)defineSetter.call(obj,prop,descriptor.set);return obj};if(!Object.getOwnPropertyDescriptor)Object.getOwnPropertyDescriptor=function(obj,prop){if(arguments.length<2)throw new TypeError("Arguments not optional.");prop+="";var descriptor={configurable:true,enumerable:true,writable:true},getter=lookupGetter.call(obj,prop),setter=lookupSetter.call(obj,prop);if(!hasOwnProp.call(obj,
prop))return descriptor;if(!getter&&!setter){descriptor.value=obj[prop];return descriptor}delete descriptor.writable;descriptor.get=descriptor.set=undefined;if(getter)descriptor.get=getter;if(setter)descriptor.set=setter;return descriptor};if(!Object.defineProperties)Object.defineProperties=function(obj,props){var prop;for(prop in props)if(hasOwnProp.call(props,prop))Object.defineProperty(obj,prop,props[prop])}}})();if(!document.documentElement.dataset&&(!Object.getOwnPropertyDescriptor(Element.prototype,
"dataset")||!Object.getOwnPropertyDescriptor(Element.prototype,"dataset").get)){var propDescriptor={enumerable:true,get:function(){var i,that=this,HTML5_DOMStringMap,attrVal,attrName,propName,attribute,attributes=this.attributes,attsLength=attributes.length,toUpperCase=function(n0){return n0.charAt(1).toUpperCase()},getter=function(){return this},setter=function(attrName,value){return typeof value!=="undefined"?this.setAttribute(attrName,value):this.removeAttribute(attrName)};try{({}).__defineGetter__("test",
function(){});HTML5_DOMStringMap={}}catch(e1){HTML5_DOMStringMap=document.createElement("div")}for(i=0;i<attsLength;i++){attribute=attributes[i];if(attribute&&(attribute.name&&/^data-\w[\w\-]*$/.test(attribute.name))){attrVal=attribute.value;attrName=attribute.name;propName=attrName.substr(5).replace(/-./g,toUpperCase);try{Object.defineProperty(HTML5_DOMStringMap,propName,{enumerable:this.enumerable,get:getter.bind(attrVal||""),set:setter.bind(that,attrName)})}catch(e2){HTML5_DOMStringMap[propName]=
attrVal}}}return HTML5_DOMStringMap}};try{Object.defineProperty(Element.prototype,"dataset",propDescriptor)}catch(e){propDescriptor.enumerable=false;Object.defineProperty(Element.prototype,"dataset",propDescriptor)}}(function(){var lastTime=0;var vendors=["ms","moz","webkit","o"];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+"RequestAnimationFrame"];window.cancelAnimationFrame=window[vendors[x]+"CancelAnimationFrame"]||window[vendors[x]+
"CancelRequestAnimationFrame"]}if(!window.requestAnimationFrame)window.requestAnimationFrame=function(callback,element){var currTime=(new Date).getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall)},timeToCall);lastTime=currTime+timeToCall;return id};if(!window.cancelAnimationFrame)window.cancelAnimationFrame=function(id){clearTimeout(id)}})();var salvattore=function(global,document,undefined){var self={},grids=[];self.obtain_grid_settings=
function obtain_grid_settings(element){var computedStyle=global.getComputedStyle(element,":before"),content=computedStyle.getPropertyValue("content").slice(1,-1),matchResult=content.match(/^\s*(\d+)(?:\s?\.(.+))?\s*$/),numberOfColumns,columnClasses;if(matchResult){numberOfColumns=matchResult[1];columnClasses=matchResult[2];columnClasses=columnClasses?columnClasses.split("."):["column"]}else{matchResult=content.match(/^\s*\.(.+)\s+(\d+)\s*$/);columnClasses=matchResult[1];numberOfColumns=matchResult[2];
if(numberOfColumns)numberOfColumns=numberOfColumns.split(".")}return{numberOfColumns:numberOfColumns,columnClasses:columnClasses}};self.add_columns=function add_columns(grid,items){var settings=self.obtain_grid_settings(grid),numberOfColumns=settings.numberOfColumns,columnClasses=settings.columnClasses,columnsItems=new Array(+numberOfColumns),columnsFragment=document.createDocumentFragment(),i=numberOfColumns,selector;while(i--!==0){selector="[data-columns] > *:nth-child("+numberOfColumns+"n-"+i+
")";columnsItems.push(items.querySelectorAll(selector))}columnsItems.forEach(function append_to_grid_fragment(rows){var column=document.createElement("div"),rowsFragment=document.createDocumentFragment();column.className=columnClasses.join(" ");Array.prototype.forEach.call(rows,function append_to_column(row){rowsFragment.appendChild(row)});column.appendChild(rowsFragment);columnsFragment.appendChild(column)});grid.appendChild(columnsFragment);grid.dataset.columns=numberOfColumns};self.remove_columns=
function remove_columns(grid){var range=document.createRange();range.selectNodeContents(grid);var columns=Array.prototype.filter.call(range.extractContents().childNodes,function filter_elements(node){return node instanceof global.HTMLElement});var numberOfColumns=columns.length,numberOfRowsInFirstColumn=columns[0].childNodes.length,sortedRows=new Array(numberOfRowsInFirstColumn*numberOfColumns);Array.prototype.forEach.call(columns,function iterate_columns(column,columnIndex){Array.prototype.forEach.call(column.children,
function iterate_rows(row,rowIndex){sortedRows[rowIndex*numberOfColumns+columnIndex]=row})});var container=document.createElement("div");container.dataset.columns=0;sortedRows.filter(function filter_non_null(child){return!!child}).forEach(function append_row(child){container.appendChild(child)});return container};self.recreate_columns=function recreate_columns(grid){global.requestAnimationFrame(function render_after_css_media_query_change(){self.add_columns(grid,self.remove_columns(grid))})};self.media_query_change=
function media_query_change(mql){if(mql.matches)Array.prototype.forEach.call(grids,self.recreate_columns)};self.get_css_rules=function get_css_rules(stylesheet){var cssRules;try{cssRules=stylesheet.sheet.cssRules}catch(e){return[]}return cssRules||[]};self.get_stylesheets=function get_stylesheets(){return Array.prototype.concat.call(Array.prototype.slice.call(document.querySelectorAll("style[type='text/css']")),Array.prototype.slice.call(document.querySelectorAll("link[rel='stylesheet']")))};self.media_rule_has_columns_selector=
function media_rule_has_columns_selector(rules){var i=rules.length,rule;while(i--){rule=rules[i];if(rule.selectorText.match(/\[data-columns\](.*)::?before$/))return true}return false};self.scan_media_queries=function scan_media_queries(){var mediaQueries=[];if(!global.matchMedia)return;self.get_stylesheets().forEach(function extract_rules(stylesheet){Array.prototype.forEach.call(self.get_css_rules(stylesheet),function filter_by_column_selector(rule){if(rule.media&&self.media_rule_has_columns_selector(rule.cssRules))mediaQueries.push(global.matchMedia(rule.media.mediaText))})});
mediaQueries.forEach(function listen_to_changes(mql){mql.addListener(self.media_query_change)})};self.next_element_column_index=function next_element_column_index(grid){var children=grid.children,m=children.length,highestRowCount,child,currentRowCount,i=children.length-1;for(i;i>=0;i--){child=children[i];currentRowCount=child.children.length;if(i!==0&&highestRowCount>currentRowCount)break;else if(i+1===m){i=0;break}highestRowCount=currentRowCount}return i};self.create_list_of_fragments=function create_list_of_fragments(quantity){var fragments=
new Array(quantity),i=0;while(i!==quantity){fragments[i]=document.createDocumentFragment();i++}return fragments};self.append_elements=function append_elements(grid,elements){var columns=grid.children,numberOfColumns=columns.length,fragments=self.create_list_of_fragments(numberOfColumns),columnIndex=self.next_element_column_index(grid);elements.forEach(function append_to_next_fragment(element){fragments[columnIndex].appendChild(element);if(columnIndex===numberOfColumns-1)columnIndex=0;else columnIndex++});
Array.prototype.forEach.call(columns,function insert_column(column,index){column.appendChild(fragments[index])})};self.prepend_elements=function prepend_elements(grid,elements){var columns=grid.children,numberOfColumns=columns.length,fragments=self.create_list_of_fragments(numberOfColumns),columnIndex=numberOfColumns-1;elements.forEach(function append_to_next_fragment(element){var fragment=fragments[columnIndex];fragment.insertBefore(element,fragment.firstChild);if(columnIndex===0)columnIndex=numberOfColumns-
1;else columnIndex--});Array.prototype.forEach.call(columns,function insert_column(column,index){column.insertBefore(fragments[index],column.firstChild)});var fragment=document.createDocumentFragment(),numberOfColumnsToExtract=elements.length%numberOfColumns;while(numberOfColumnsToExtract--!==0)fragment.appendChild(grid.lastChild);grid.insertBefore(fragment,grid.firstChild)};self.register_grid=function register_grid(grid){if(global.getComputedStyle(grid).display==="none")return;var range=document.createRange();
range.selectNodeContents(grid);var items=document.createElement("div");items.appendChild(range.extractContents());items.dataset.columns=0;self.add_columns(grid,items);grids.push(grid)};self.init=function init(){var gridElements=document.querySelectorAll("[data-columns]");Array.prototype.forEach.call(gridElements,self.register_grid);self.scan_media_queries()};self.init();return{append_elements:self.append_elements,prepend_elements:self.prepend_elements,register_grid:self.register_grid}}(window,window.document);
return salvattore});

},500);
});


